gifai/urls.py
from django.conf.urls import patterns, url
from gifai import views


urlpatterns = patterns('',
                       url(r'^top/', views.index_by_score, name='index_by_score'),
                       url(r'^$', views.index, name='index'),
                       url(r'^submit/', views.submit, name='submit'),
                       url(r'^(?P<gif_id>\d+)/$', views.detail, name='detail'),
                       url(r'^(?P<gif_id>\d+)/vote/$', views.vote, name='vote'),
)

gifs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = patterns('',
                       url(r'^$', RedirectView.as_view(pattern_name='gifai:index')),
                       url(r'^gifai/', include('gifai.urls', namespace='gifai')),
                       url(r'^admin/', include(admin.site.urls)),
)

gifai/models.py
from datetime import datetime

from django.db import models


class Gif(models.Model):
    pub_date = models.DateTimeField(auto_now_add=True, default=datetime.now())
    pub_date.editable = True
    title = models.CharField(max_length=200)
    source = models.URLField(max_length=200)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

# Create your models here.

gifai/forms.py
from django.forms import ModelForm

from gifai.models import Gif


class GifForm(ModelForm):
    class Meta:
        model = Gif
        fields = ['title', 'source']
        # title = forms.CharField(label="Title", max_length=200)
    #url = forms.URLField(label="URL")

gifai/views.py
import urllib2
import re

from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from gifai.models import Gif
from gifai.forms import GifForm


def index(request):
    gif_list = Gif.objects.all().order_by('-pub_date')
    context = {'gif_list': gif_list, 'sort': 'new'}
    return render(request, 'gifai/index.html', context)


def index_by_score(request):
    gif_list = Gif.objects.all().order_by('-score')
    context = {'gif_list': gif_list, 'sort': 'top'}
    return render(request, 'gifai/index.html', context)


def image_exists(url):
    re_image = re.compile("([^\\s]+(\\.(?i)(/bmp|jpg|jpeg|gif|png))$)")
    try:
        f = urllib2.urlopen(urllib2.Request(url))
        if re_image.match(url):
            return True
    except:
        return False
    return False


def submit(request):
    if request.method == "POST":
        form = GifForm(request.POST)
        if form.is_valid():
            form_obj = form.save(commit=False)
            if image_exists(form_obj.source):
                form_obj.save()
                return HttpResponseRedirect(reverse('gifai:detail', args=(form_obj.id,)))
            return render(request, "gifai/submit.html", {'form': form, 'error': 'URL was not an image'})
            # return render(request, 'gifai/submit.html')
    form = GifForm()
    return render(request, "gifai/submit.html", {'form': form})


def detail(request, gif_id):
    try:
        gif = Gif.objects.get(pk=gif_id)
        context = {'gif': gif}
    except Gif.DoesNotExist:
        raise Http404
    return render(request, 'gifai/detail.html', context)


# return HttpResponse("looking at %s" % pk)
def vote(request, gif_id):
    g = get_object_or_404(Gif, pk=gif_id)
    if request.POST.get('vote') == 'upvote':
        g.score += 1
    elif request.POST.get('vote') == 'downvote':
        g.score -= 1
    g.save()
    return HttpResponseRedirect(reverse('gifai:detail', args=(g.id,)))

#return HttpResponse('at id G.ID %s' % g.id)

gifai/templates/gifai/base_header.html
<!DOCTYPE html>

<style>
    div {
        background-color: #ccffcc;
    }

    div.gifbox {
        width: 400px;
        border: 1px solid;
    }

    div.upperhalf {
        height: 20px;
    }

    p.titlebox {
        float: left;
        margin: 0px;
    }

    p.scorebox {
        float: right;
        margin: 0px;
    }
</style>
<html>
<head>
    <title>Imgooor</title>
</head>

<body>
<div>
    <h1>
        <a href="{% url 'gifai:index' %}">Imgooor</a>
    </h1>
</div>

{% block content %}
{% endblock %}
</body>
</html>

gifai/templates/gifai/detail.html
{% extends 'gifai/base_header.html' %}

{% block content %}
<h2>{{gif.title}}</h2>

<a href="{{gif.source}}">
    <img src="{{gif.source}}" height="200" width="200"/></a>

<br>
Submitted: {{ gif.pub_date|date:"Y M d H:i" }}
<br>
Votecount: {{gif.score}}

<form action="{% url 'gifai:vote' gif.id %}" method="post">
    {% csrf_token %}
    <button type="submit" name="vote" value="upvote">Upvote</button>
    <button type="submit" name="vote" value="downvote">Downvote</button>

</form>
{% endblock content %}

gifai/templates/gifai/index.html
{% extends 'gifai/base_header.html' %}
{% block content %}
{% if gif_list %}
{% if sort == 'new' %}
<a href="{% url 'gifai:index_by_score' %}">Sort by rating</a>
{% elif sort == 'top' %}
<a href="{% url 'gifai:index' %}">Sort by date</a>
{% endif %}

<a href="{% url 'gifai:submit' %}">Submit a new pic</a>
<ol>
    {%for gif in gif_list %}
    <li>
        <div class="gifbox">
            <div class="upperhalf">
                <p class="titlebox">
                    <a href="/gifai/{{gif.id}}">
                        {{gif.title}}
                    </a>
                </p>

                <p class="scorebox">
                    {% if sort == 'new' %}
                    {{ gif.pub_date|date:"Y M d H:i" }}
                    {% elif sort = 'top' %}
                    {{gif.score}} vote{{gif.score|pluralize}}
                    {% endif %}
                </p>
            </div>
            <div>
                <a href="/gifai/{{gif.id}}">
                    <img src="{{gif.source}}" title="{{gif.title}}" height="100" width="100" class="miniimg"/>
                </a>
            </div>
        </div>
    </li>
    {% endfor %}
</ol>
{% else %}
<p>No gifs available.</p>
{% endif %}
{% endblock content %}

gifai/templates/gifai/submit.html
<style>

    p.error {
        color: red
    }

</style>

<form action="{% url 'gifai:submit' %}" method="post">
    {% csrf_token %}
    {{form}}
    <button class="submitbutton" name="submit" value="submit">Submit</button>
    {% if error %}
    <br>

    <p class="error">{{error}}</p>
    {% endif %}
</form>